name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.86
        components: rustfmt, clippy
        override: true
    
    - name: Cache cargo registry and target directory
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest
    
    - name: Build
      run: cargo build --verbose --profile ci
    
    - name: Run Tests
      run: cargo nextest run --profile ci --workspace --all-features
      
    - name: Run Clippy
      run: cargo clippy --profile ci -- -D warnings
      
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Run Benchmarks
      run: cargo bench --profile ci || true